import DOWN_ARROW from '../../../assets/down-arrow.png'
import ROCKET from '../../../assets/rocket.png'


export default function Banner() {
  return (
    <div className='text-center py-24 px-3 lg:px-0'>
      <div className='max-w-[650px] mx-auto space-y-10 mb-14'>
        <h3 className="uppercase text-[#CFCFCF]">Welcome to MONISWAP</h3>
        <h2 className="text-4xl md:text-5xl italic text-[#fff]">The central hub for trading & liquidity marketplace on 🐻 Berachain</h2>
        <div className='w-32 h-32 mx-auto rounded-full bg-gradient-to-b from-[#ffbf60] to-[#fcb415] flex items-center justify-center'>
          <div>
            <img className='mx-auto mb-2' src={ROCKET} alt="" />
            <span className='text-white'>Swap</span>
          </div>
        </div>

        <img className='mx-auto' src={DOWN_ARROW} alt="" />
      </div>
      <div className='max-w-[700px] mx-auto'>
        <p className='text-lg italic text-[#CFCFCF]'>Moniswap represents the next evolution of automated market makers (AMMs) and serves as the central liquidity hub for 🐻 Berachain. It integrates a robust liquidity incentive engine, a governance model based on vote-lock mechanisms. Leveraging the latest features from Velodrome V2, Moniswap NFTs vote to distribute token emissions and receive incentives and fees generated by the protocol.</p>
      </div>
    </div>
  )
}
